packageExtensions:
  '@ethereumjs/vm@*':
    dependencies:
      rlp: '*'
  '@renproject/chains@*':
    dependencies:
      send-crypto: '*'
  '@renproject/utils@*':
    dependencies:
      web3-utils: '*'
  web3-eth@*:
    dependencies:
      bs58: '*'
  'follow-redirects@*':
    dependencies:
      debug: '*'
      lodash: '*'
  'hardhat-deploy@*':
    dependencies:
      '@ethersproject/constants': '^5.0.0'
  '@augurproject/smart@*':
    dependencies:
      'hardhat': '^2.1.1'
      'hardhat-deploy': '^0.7.5'
      'tslib': '^2.3.1'
      'ethers': '^5.0.0'
      '@ethersproject/signing-key': '^5.0.0'
      '@ethersproject/abstract-provider': '^5.0.0'
      '@ethersproject/abstract-signer': '^5.0.0'
      '@ethersproject/bytes': '^5.0.0'
      '@ethersproject/providers': '^5.0.0'
      'luxon': '^2.0.2'
      '@types/luxon': '^2.0.0'
      'eslint-config-prettier': '^8.1.0'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.0.0.cjs
